Repository bbc/digital-paper-edit-firebase, pull requests merged in 2020-05, with the labels that each got.

#90 Updating time to expire
  functions/package-lock.json
  functions/sttChecker/index.js
Labels: devOps

#96 Fix manual colour selection in label form
  src/Components/PaperEditor/TranscriptsContainer/LabelsList/LabelForm.js
Labels: bug

#91 Functions updates status for transcription Job
  functions/inventoryChecker/index.js
  functions/package-lock.json
  functions/sttChecker/index.js
Labels: enhancement, firebase

#67 [Update]: Pass word timing to PreviewCanvas on double click
  package-lock.json
  package.json
  src/Components/PaperEditor/ProgrammeScriptContainer/index.js
  src/Components/PaperEditor/ProgrammeScriptContainer/reset-word-timings.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/index.js
Labels: enhancement

#113 Saved notification does not reappear and does not show the error version of Alert on firestore operations.
  src/App.js
  src/Components/Firebase/Collection.js
  src/Components/Workspace/Transcripts/TranscriptEditor.js
Labels: bug

#112 Gzip transcriptions
  functions/package-lock.json
  functions/package.json
  functions/sttChecker/index.js
  package-lock.json
  package.json
  src/Components/Firebase/firebase.js
  src/Components/PaperEditor/index.js
  src/Components/Workspace/Transcripts/TranscriptEditor.js
  src/Components/Workspace/Transcripts/index.js
  src/Components/lib/ItemsContainer/index.js
  src/Util/gzip/index.js
Labels: enhancement

#115 Adding runtime to database
  functions/sttChecker/index.js
Labels: enhancement

#116 Adding improvements to too many useEffect re-renders + calling
  src/Components/PaperEditor/index.js
  src/Components/Workspace/Transcripts/TranscriptEditor.js
  src/Util/gzip/index.js
Labels: enhancement

#117 Bug fix - Prevent white outs on create projects / paper edits
  src/Components/Projects/index.js
  src/Components/Workspace/PaperEdits/index.js
Labels: bug

#118 Lazy loading
  src/Components/PaperEditor/ProgrammeScriptContainer/Article/index.js
  src/Components/PaperEditor/ProgrammeScriptContainer/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/index.js
Labels: bug

#119 Improve Performance using Memo, Suspense / Lazy, and refactor
  src/Components/PaperEditor/ProgrammeScriptContainer/index.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/Paragraph.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/Word.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/group-words-by-speakers.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptMenu/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptNavItem/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabPane/index.js
  src/Components/PaperEditor/TranscriptsContainer/index.js
  src/Components/PaperEditor/index.js
  src/Util/gzip/index.js
Labels: enhancement

#121 Removing a bunch of problematic async/awaits that make things synchro…
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/index.js
  src/Components/Workspace/Transcripts/index.js
Labels: bug

#122 Default active tab for transcription is successful tab
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabPane/TranscriptTabContent/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabPane/index.js
  src/Components/PaperEditor/TranscriptsContainer/index.js
Labels: bug

#126 Functions update to retrospectively update everything to a single grouped entry in GZIP
  functions/compressData/index.js
  functions/index.js
  functions/sttChecker/index.js
  functions/sttChecker/psttAdapter.js
  functions/test/index.test.js
  functions/test/psttAdapter.test.js
  functions/utils/firebase.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabPane/TranscriptTabContent/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabPane/index.js
  src/Components/PaperEditor/TranscriptsContainer/index.js
  src/Components/Workspace/Transcripts/TranscriptEditor.js
  src/Components/Workspace/Transcripts/group-words-by-speakers.js
Labels: enhancement
