Repository bbc/digital-paper-edit-firebase, pull requests merged in 2020-04, with the labels that each got.

#66 Make Card URL an empty string, in case nothing has been set yet.
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/add-annotations-to-words-in-paragraphs.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/find-annotation-in-paragraph.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/group-words-by-speakers.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/index.js
  src/Components/PaperEditor/TranscriptsContainer/Transcript.js
  src/Components/PaperEditor/TranscriptsContainer/index.js
  src/Components/PaperEditor/index.js
  src/Components/Workspace/PaperEdits/index.js
  src/Components/lib/ItemsContainer/index.js
Labels: bug

#68 Refactored Transcript Container so it is easier to understand, will…
  src/Components/PaperEditor/ProgrammeScriptContainer/index.js
  src/Components/PaperEditor/TranscriptsContainer/LabelsList/index.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/AnnotationOverlayTrigger.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/index.js
  src/Components/PaperEditor/TranscriptsContainer/SearchBar/index.js
  src/Components/PaperEditor/TranscriptsContainer/Transcript.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/TranscriptMenu.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/index.js
  src/Components/PaperEditor/TranscriptsContainer/index.js
  src/Components/PaperEditor/index.js
  src/Components/Workspace/Transcripts/TranscriptEditor.js
Labels: enhancement

#72 I47 add annotations
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/AnnotationOverlayTrigger.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/add-annotations-to-words-in-paragraphs.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/find-annotation-in-paragraph.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/TranscriptMenu.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/index.js
  src/Components/PaperEditor/index.js
Labels: enhancement, firebase

#76 i73-adds-default-label
  src/Components/Projects/index.js
  src/Components/Workspace/PaperEdits/index.js
Labels: bug, enhancement, firebase

#78 Annotation + Label Collection retrieval to where it is used. Refactoring left over functions and cleaning up Proptypes
  src/Components/PaperEditor/TranscriptsContainer/LabelsList/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/TranscriptMenu.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/index.js
  src/Components/PaperEditor/TranscriptsContainer/index.js
  src/Components/PaperEditor/index.js
Labels: enhancement

#77 Warning with having Button in a Button component
  src/Components/PaperEditor/TranscriptsContainer/LabelsList/CreateNewLabelModal.js
  src/Components/PaperEditor/TranscriptsContainer/LabelsList/LabelForm.js
  src/Components/PaperEditor/TranscriptsContainer/LabelsList/LabelModal.js
  src/Components/PaperEditor/TranscriptsContainer/LabelsList/index.js
Labels: bug

#75 I49
  src/Components/PaperEditor/TranscriptsContainer/LabelsList/index.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/AnnotationOverlayTrigger.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/Paragraph.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/Word.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/add-annotations-to-words-in-paragraphs.js
  src/Components/PaperEditor/TranscriptsContainer/Paragraphs/index.js
  src/Components/PaperEditor/TranscriptsContainer/SearchBar/index.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/TranscriptMenu.js
  src/Components/PaperEditor/TranscriptsContainer/TranscriptTabContent/index.js
  src/Util/remove-punctuation/index.js
Labels: enhancement
